### ISSUE TITLE
Make logo disappear on sticky header

### ISSUE THREAD

**Issue by EugenioPetulla** [yithemes/yith-proteo#18]
Consider to put an option in order to make the logo disappear on the sticky version of the header.

This will be a very nice to have option in the sticky section of customizer.
It's very easy to implement and sometime saves a lot of space, specially in the "logo centered" version of the header.

PoC:

```css
.site-header.sticky .site-branding.SHOW-BRAND-ATTR .site-title {
    display: none;
}
```
